export type PatientProfileViewProps = {
  onVoltar: () => void;
  onSalvar: () => void;
  onImprimirPulseira: () => void;
  onImprimirFolha: () => void;
  onExibirInformacoes: () => void;
  onGerarRelatorio: () => Promise<void>;
  nome: string;
  nomeSocial: string;
  dataNascimento: string;
  cpf: string;
  nomeResponsavel: string;
  telefone: string;
  prontuario: string;
  cartaoSUS: string;
  especialidade: string;
  unidade: string;
  deficiencia: string;
  salvo: boolean;
  temTEA: boolean;
  resumoTexto: string;
  nivelSuporte: string;
  autonomia: string;
  comunicacao: string;
  comunicacaoAlternativa: string;
  interacaoSocial: string[];
  fatoresDesregulacao: string[];
  dificuldadesSensoriais: string[];
  fatoresClinicos: string[];
  hiperfoco: string;
  relatorioIA: string;
  gerandoRelatorio: boolean;
  setNome: (v: string) => void;
  setNomeSocial: (v: string) => void;
  setDataNascimento: (v: string) => void;
  setCpf: (v: string) => void;
  setNomeResponsavel: (v: string) => void;
  setTelefone: (v: string) => void;
  setProntuario: (v: string) => void;
  setCartaoSUS: (v: string) => void;
  setEspecialidade: (v: string) => void;
  setUnidade: (v: string) => void;
  setDeficiencia: (v: string) => void;
  setNivelSuporte: (v: string) => void;
  setAutonomia: (v: string) => void;
  setComunicacao: (v: string) => void;
  setComunicacaoAlternativa: (v: string) => void;
  setHiperfoco: (v: string) => void;
  toggleInteracaoSocial: (item: string) => void;
  toggleFatoresDesregulacao: (item: string) => void;
  toggleDificuldadesSensoriais: (item: string) => void;
  toggleFatoresClinicos: (item: string) => void;
};
